type StartMessage = { type: 'start'; runId: string; totalBytes: number; chunkBytes: number };
type CancelMessage = { type: 'cancel'; runId: string };
type WorkerMessage = StartMessage | CancelMessage;

type WorkerScope = {
  onmessage: ((event: MessageEvent<WorkerMessage>) => void) | null;
  postMessage: (message: unknown) => void;
};

const workerScope = self as unknown as WorkerScope;
let activeRunId: string | null = null;

function yieldToMessages() {
  // This is a control-path fixture, not a throughput benchmark. A short,
  // cooperative cadence keeps progress and cancellation observable to humans.
  return new Promise<void>((resolve) => setTimeout(resolve, 40));
}

async function runGeneratedStream(message: StartMessage) {
  activeRunId = message.runId;
  const startedAt = performance.now();
  const chunk = new Uint8Array(message.chunkBytes);
  let processedBytes = 0;
  let checksum = 0;
  let chunkIndex = 0;

  while (processedBytes < message.totalBytes && activeRunId === message.runId) {
    const remaining = message.totalBytes - processedBytes;
    const bytesThisChunk = Math.min(message.chunkBytes, remaining);
    chunk.fill((chunkIndex * 37 + 11) % 251, 0, bytesThisChunk);

    // Touch one byte per 4 KiB page. The full chunk is generated by fill(), while
    // the page walk supplies a deterministic integrity signal without retaining it.
    for (let offset = 0; offset < bytesThisChunk; offset += 4096) {
      checksum = (checksum + chunk[offset] * ((offset >>> 12) + 1)) >>> 0;
    }

    processedBytes += bytesThisChunk;
    chunkIndex += 1;

    if (chunkIndex % 4 === 0 || processedBytes === message.totalBytes) {
      workerScope.postMessage({
        type: 'progress',
        runId: message.runId,
        processedBytes,
        totalBytes: message.totalBytes,
        elapsedMs: performance.now() - startedAt,
      });
    }

    if (chunkIndex % 2 === 0 || processedBytes === message.totalBytes) {
      await yieldToMessages();
    }
  }

  if (activeRunId !== message.runId) {
    workerScope.postMessage({
      type: 'cancelled',
      runId: message.runId,
      processedBytes,
      totalBytes: message.totalBytes,
      elapsedMs: performance.now() - startedAt,
    });
    return;
  }

  workerScope.postMessage({
    type: 'complete',
    runId: message.runId,
    processedBytes,
    totalBytes: message.totalBytes,
    elapsedMs: performance.now() - startedAt,
    checksum: checksum.toString(16).padStart(8, '0'),
  });
  activeRunId = null;
}

workerScope.onmessage = (event) => {
  const message = event.data;
  if (message.type === 'cancel') {
    if (activeRunId === message.runId) activeRunId = null;
    return;
  }
  if (activeRunId) return;
  void runGeneratedStream(message);
};

export {};
