// frontend/src/motion/parity/motionParity.test.ts
/**
 * THE Phase 1a gate: compareNormalized must reproduce the real Java engine's
 * outputs on every oracle case, within the two-tier tolerances from the handoff:
 *   round(_,2) fields  -> |d| <= 0.01
 *   round(_,6) fields  -> |d| <= 2e-6
 *   degree fields (round 3) -> |d| <= 2e-3
 *   verdict / booleans / counts -> exact
 * Oracle: motion-parity-oracle.json, generated by MotionParityOracleGeneratorTest
 * on the shipping Maven JVM. Never regenerate it to make this test pass.
 * (sample()'s span==0 branch is unreachable via valid input — unique keyframe
 * times are enforced by Java validation — so no oracle case covers it.)
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { NormalizedAnimationJson } from '../normalizedMotion';
import { compareNormalized, type NormalizedComparisonResult } from '../motionEngineCore';

interface OracleCase {
  id: string;
  description: string;
  source: NormalizedAnimationJson;
  candidate: NormalizedAnimationJson;
  result: {
    algorithmVersion: string;
    overallPercent: number;
    posePercent: number;
    timingPercent: number;
    coveragePercent: number;
    exactCurveData: boolean;
    verdict: string;
    jointScores: Array<{
      jointPath: string; presentInSource: boolean; presentInCandidate: boolean;
      posePercent: number; meanPositionDelta: number; maxPositionDelta: number;
      meanRotationDeltaDegrees: number; maxRotationDeltaDegrees: number;
    }>;
    frameScores: Array<{
      sampleIndex: number; normalizedTime: number; sourceTime: number;
      candidateTime: number; posePercent: number; comparedJointCount: number;
    }>;
  };
}

const oracle = JSON.parse(
  readFileSync(new URL('./motion-parity-oracle.json', import.meta.url), 'utf8'),
) as { cases: OracleCase[] };

// 0.0105, not 0.01: the handoff allows an adjacent-hundredth rounding straddle
// (Java rounds x.xx5 up, TS lands a hair below), and the float64 representation of
// that exactly-0.01 difference computes as 0.0100000000000051 — strict >0.01 would
// spuriously fail the designed-allowed case. Anything beyond one hundredth still fails.
const ROUND2 = 0.0105;
const ROUND6 = 2e-6;
const DEGREES = 2e-3;

function check(failures: string[], path: string, actual: number, expected: number, tolerance: number) {
  if (!Number.isFinite(actual) || Math.abs(actual - expected) > tolerance) {
    failures.push(`${path}: TS ${actual} vs Java ${expected} (|d|=${Math.abs(actual - expected)} > ${tolerance})`);
  }
}

describe('Java parity oracle', () => {
  it('has the expected case inventory', () => {
    expect(oracle.cases.length).toBe(22);
    expect(new Set(oracle.cases.map((entry) => entry.id)).size).toBe(22);
  });

  it.each(oracle.cases.map((entry) => [entry.id, entry] as const))('%s', (_id, oracleCase) => {
    const actual: NormalizedComparisonResult = compareNormalized(oracleCase.source, oracleCase.candidate);
    const expected = oracleCase.result;
    const failures: string[] = [];

    expect(actual.algorithmVersion).toBe(expected.algorithmVersion);
    expect(actual.exactCurveData).toBe(expected.exactCurveData);
    expect(actual.verdict).toBe(expected.verdict);
    check(failures, 'overallPercent', actual.overallPercent, expected.overallPercent, ROUND2);
    check(failures, 'posePercent', actual.posePercent, expected.posePercent, ROUND2);
    check(failures, 'timingPercent', actual.timingPercent, expected.timingPercent, ROUND2);
    check(failures, 'coveragePercent', actual.coveragePercent, expected.coveragePercent, ROUND2);

    expect(actual.jointScores.length).toBe(expected.jointScores.length);
    for (let i = 0; i < expected.jointScores.length; i += 1) {
      const a = actual.jointScores[i];
      const e = expected.jointScores[i];
      expect(a.jointPath).toBe(e.jointPath);
      expect(a.presentInSource).toBe(e.presentInSource);
      expect(a.presentInCandidate).toBe(e.presentInCandidate);
      check(failures, `jointScores[${e.jointPath}].posePercent`, a.posePercent, e.posePercent, ROUND2);
      check(failures, `jointScores[${e.jointPath}].meanPositionDelta`, a.meanPositionDelta, e.meanPositionDelta, ROUND6);
      check(failures, `jointScores[${e.jointPath}].maxPositionDelta`, a.maxPositionDelta, e.maxPositionDelta, ROUND6);
      check(failures, `jointScores[${e.jointPath}].meanRotationDeltaDegrees`, a.meanRotationDeltaDegrees, e.meanRotationDeltaDegrees, DEGREES);
      check(failures, `jointScores[${e.jointPath}].maxRotationDeltaDegrees`, a.maxRotationDeltaDegrees, e.maxRotationDeltaDegrees, DEGREES);
    }

    expect(actual.frameScores.length).toBe(expected.frameScores.length);
    for (let i = 0; i < expected.frameScores.length; i += 1) {
      const a = actual.frameScores[i];
      const e = expected.frameScores[i];
      expect(a.sampleIndex).toBe(e.sampleIndex);
      expect(a.comparedJointCount).toBe(e.comparedJointCount);
      check(failures, `frameScores[${i}].normalizedTime`, a.normalizedTime, e.normalizedTime, ROUND6);
      check(failures, `frameScores[${i}].sourceTime`, a.sourceTime, e.sourceTime, ROUND6);
      check(failures, `frameScores[${i}].candidateTime`, a.candidateTime, e.candidateTime, ROUND6);
      check(failures, `frameScores[${i}].posePercent`, a.posePercent, e.posePercent, ROUND2);
    }

    expect(failures, `\n${failures.join('\n')}`).toEqual([]);
  });
});
