// frontend/src/motion/parity/v2Parity.test.ts
/**
 * THE gate that keeps engine v2 one algorithm in two languages.
 *
 * `compareMotion` (browser) must reproduce `MotionComparisonEngineV2.compare` (the Studio plugin
 * route) on every oracle case, within the same two-tier tolerances the v1 parity gate uses:
 *   round(_,2) fields       -> |d| <= 0.01
 *   round(_,6) fields       -> |d| <= 2e-6
 *   degree fields (round 3) -> |d| <= 2e-3
 *   verdict / booleans / counts -> exact
 *
 * WHY IT EXISTS. Issue #102: every browser surface scored on v2 while the plugin route still scored
 * on v1, so the same pair got different numbers depending on which door it came through, and a
 * mirrored copy was caught in the browser and missed through the plugin. v1 has had a parity gate
 * since Phase 1a. v2 shipped four divergences with none — which is exactly how the two sides drifted
 * apart while both suites stayed green. A second implementation is only safe if something binds it.
 *
 * Oracle: motion-v2-parity-oracle.json, generated by MotionV2ParityOracleGeneratorTest on the
 * shipping Maven JVM. Never regenerate it to make this test pass — that converts a detected
 * divergence into a silent one, which is the whole defect being fixed.
 *
 * NOT compared, and deliberately: `limitations` (Java-only evidence prose, no TS counterpart),
 * the asset ids, and the fingerprints (v1's SHA-256 canonical digest has no TS implementation —
 * the port replaces it with structural canonical equality, which is what `exactCurveData` grades).
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { NormalizedAnimationJson } from '../normalizedMotion';
import { compareMotion, ENGINE_V2_VERSION, type MotionComparisonV2 } from '../motionEngine';

interface OracleCase {
  id: string;
  description: string;
  source: NormalizedAnimationJson;
  candidate: NormalizedAnimationJson;
  result: {
    engineVersion: string;
    overallPercent: number;
    posePercent: number;
    timingPercent: number;
    coveragePercent: number;
    durationPercent: number;
    warpScore: number;
    exactCurveData: boolean;
    verdict: string;
    mirrored: boolean;
    commonJointCount: number;
    allJointCount: number;
    jointScores: Array<{
      jointPath: string; presentInSource: boolean; presentInCandidate: boolean;
      posePercent: number; meanPositionDelta: number; maxPositionDelta: number;
      meanRotationDeltaDegrees: number; maxRotationDeltaDegrees: number;
    }>;
    frameScores: Array<{ sampleIndex: number; posePercent: number }>;
  };
}

const oracle = JSON.parse(
  readFileSync(new URL('./motion-v2-parity-oracle.json', import.meta.url), 'utf8'),
) as { engineVersion: string; cases: OracleCase[] };

// Same straddle allowance as the v1 gate: Java rounds x.xx5 up, TS lands a hair below, and the
// float64 representation of that exactly-0.01 difference computes as 0.0100000000000051.
const ROUND2 = 0.0105;
const ROUND6 = 2e-6;
const DEGREES = 2e-3;

function check(failures: string[], path: string, actual: number, expected: number, tolerance: number) {
  if (!Number.isFinite(actual) || !Number.isFinite(expected) || Math.abs(actual - expected) > tolerance) {
    failures.push(`${path}: TS ${actual} vs Java ${expected} (|d|=${Math.abs(actual - expected)} > ${tolerance})`);
  }
}

describe('Java engine-v2 parity oracle', () => {
  it('agrees on the engine version string', () => {
    // Both sides must report the SAME version, or the comparison table holds two names for one
    // algorithm again — the confusion #102 is about.
    expect(oracle.engineVersion).toBe(ENGINE_V2_VERSION);
  });

  it('has the expected case inventory', () => {
    expect(oracle.cases.length).toBe(30);
    expect(new Set(oracle.cases.map((entry) => entry.id)).size).toBe(30);
    // The mirror cases are the ones v1's list cannot cover, since not one of its animations has a
    // left/right joint name. If this count drops, the mirror half of the port lost its grader.
    expect(oracle.cases.filter((entry) => entry.id.startsWith('v2-mirror-')).length).toBe(7);
  });

  it('exercises the mirrored branch on both sides', () => {
    // A gate that never takes the mirrored orientation would pass while proving nothing about it.
    const mirroredCases = oracle.cases.filter((entry) => entry.result.mirrored);
    expect(mirroredCases.length).toBeGreaterThanOrEqual(4);
    for (const entry of mirroredCases) {
      const actual = compareMotion(entry.source, entry.candidate);
      expect(actual.mirrored, `${entry.id} should mirror in TS too`).toBe(true);
    }
  });

  it.each(oracle.cases.map((entry) => [entry.id, entry] as const))('%s', (_id, oracleCase) => {
    const actual: MotionComparisonV2 = compareMotion(oracleCase.source, oracleCase.candidate);
    const expected = oracleCase.result;
    const failures: string[] = [];

    expect(actual.engineVersion).toBe(expected.engineVersion);
    expect(actual.exactCurveData).toBe(expected.exactCurveData);
    expect(actual.verdict).toBe(expected.verdict);
    expect(actual.mirrored).toBe(expected.mirrored);
    expect(actual.commonJointCount).toBe(expected.commonJointCount);
    expect(actual.allJointCount).toBe(expected.allJointCount);

    check(failures, 'overallPercent', actual.overallPercent, expected.overallPercent, ROUND2);
    check(failures, 'posePercent', actual.posePercent, expected.posePercent, ROUND2);
    check(failures, 'timingPercent', actual.timingPercent, expected.timingPercent, ROUND2);
    check(failures, 'coveragePercent', actual.coveragePercent, expected.coveragePercent, ROUND2);
    check(failures, 'durationPercent', actual.durationPercent, expected.durationPercent, ROUND2);
    check(failures, 'warpScore', actual.warpScore, expected.warpScore, ROUND2);

    expect(actual.jointScores.length).toBe(expected.jointScores.length);
    for (let i = 0; i < expected.jointScores.length; i += 1) {
      const a = actual.jointScores[i];
      const e = expected.jointScores[i];
      expect(a.jointPath).toBe(e.jointPath);
      expect(a.presentInSource).toBe(e.presentInSource);
      expect(a.presentInCandidate).toBe(e.presentInCandidate);
      check(failures, `jointScores[${e.jointPath}].posePercent`, a.posePercent, e.posePercent, ROUND2);
      check(failures, `jointScores[${e.jointPath}].meanPositionDelta`, a.meanPositionDelta, e.meanPositionDelta, ROUND6);
      check(failures, `jointScores[${e.jointPath}].maxPositionDelta`, a.maxPositionDelta, e.maxPositionDelta, ROUND6);
      check(failures, `jointScores[${e.jointPath}].meanRotationDeltaDegrees`, a.meanRotationDeltaDegrees, e.meanRotationDeltaDegrees, DEGREES);
      check(failures, `jointScores[${e.jointPath}].maxRotationDeltaDegrees`, a.maxRotationDeltaDegrees, e.maxRotationDeltaDegrees, DEGREES);
    }

    expect(actual.frameScores.length).toBe(expected.frameScores.length);
    for (let i = 0; i < expected.frameScores.length; i += 1) {
      expect(actual.frameScores[i].sampleIndex).toBe(expected.frameScores[i].sampleIndex);
      check(failures, `frameScores[${i}].posePercent`, actual.frameScores[i].posePercent, expected.frameScores[i].posePercent, ROUND2);
    }

    expect(failures, `\n${failures.join('\n')}`).toEqual([]);
  });
});
