// core/src/test/java/creatorflow/motion/MotionV2ParityOracleGeneratorTest.java
package creatorflow.motion;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

/**
 * Generates (UPDATE_MOTION_V2_ORACLE=1) or drift-guards the committed engine-v2 parity oracle at
 * frontend/src/motion/parity/motion-v2-parity-oracle.json.
 *
 * <p>This is the gate that stops issue #102 recurring. The plugin route scores in Java and every
 * browser surface scores in TypeScript; the only thing that keeps those two the same algorithm is
 * this oracle plus v2Parity.test.ts on the other side. v1 has had that protection since Phase 1a —
 * v2 shipped four divergences without it, which is precisely how the two engines drifted apart while
 * both test suites stayed green.
 *
 * <p>Never regenerate to make a failing TS parity test pass: that inverts the oracle and converts a
 * detected divergence into a silent one.
 */
class MotionV2ParityOracleGeneratorTest {

    private static final Path ORACLE_PATH =
            Path.of("..", "frontend", "src", "motion", "parity", "motion-v2-parity-oracle.json");

    @Test
    void oracleMatchesTheCommittedFixture() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode oracle = mapper.createObjectNode();
        oracle.put("generatorNote",
                "Generated by MotionV2ParityOracleGeneratorTest via mvn -pl core test; regenerate ONLY "
                        + "with UPDATE_MOTION_V2_ORACLE=1 and only to add cases.");
        oracle.put("engineVersion", MotionComparisonEngineV2.ENGINE_VERSION);
        oracle.put("javaVersion", System.getProperty("java.version"));
        oracle.put("osName", System.getProperty("os.name"));
        ArrayNode cases = oracle.putArray("cases");
        Map<String, MotionComparisonV2Result> byId = new HashMap<>();
        for (MotionV2ParityOracle.OracleCase oracleCase : MotionV2ParityOracle.cases()) {
            MotionComparisonV2Result result = MotionComparisonEngineV2.compare(
                    new MotionComparisonRequest(oracleCase.source(), oracleCase.candidate()));
            byId.put(oracleCase.id(), result);
            ObjectNode node = cases.addObject();
            node.put("id", oracleCase.id());
            node.put("description", oracleCase.description());
            node.set("source", mapper.valueToTree(oracleCase.source()));
            node.set("candidate", mapper.valueToTree(oracleCase.candidate()));
            node.set("result", mapper.valueToTree(result));
        }

        assertBranchesActuallyFired(byId);

        if ("1".equals(System.getenv("UPDATE_MOTION_V2_ORACLE"))) {
            Files.createDirectories(ORACLE_PATH.getParent());
            mapper.writerWithDefaultPrettyPrinter().writeValue(ORACLE_PATH.toFile(), oracle);
            return;
        }

        Assumptions.assumeTrue(Files.exists(ORACLE_PATH),
                "committed v2 oracle not present (frontend tree unavailable); run with UPDATE_MOTION_V2_ORACLE=1 to create it");
        JsonNode committed = mapper.readTree(ORACLE_PATH.toFile());
        // javaVersion/osName may legitimately differ between machines; the cases must not.
        assertEquals(cases, committed.get("cases"),
                "v2 oracle drift: MotionV2ParityOracle cases or engine v2 output changed without regenerating the fixture");
    }

    /**
     * Asserts the mirror cases exercised the branches they were written for.
     *
     * <p>Without this the suite would still pass if mirroring silently stopped happening — every
     * case would just record a direct comparison, the committed oracle would match, and the mirror
     * half of the port would be graded by nothing. A case whose branch does not fire is not
     * reassuring, it is uninformative, so the branch is asserted rather than assumed.
     */
    private static void assertBranchesActuallyFired(Map<String, MotionComparisonV2Result> byId) {
        for (String id : new String[] {
                "v2-mirror-trailing-suffix", "v2-mirror-infix-side-letter", "v2-mirror-left-right-word"}) {
            MotionComparisonV2Result result = byId.get(id);
            assertTrue(result.mirrored(), id + ": the mirrored orientation should have won");
            assertFalse(result.exactCurveData(),
                    id + ": a mirrored pair must never claim exact curve data");
            assertEquals(MotionVerdict.HIGH_SIMILARITY, result.verdict(),
                    id + ": a cleanly mirrored copy should land in the HIGH band, downgraded from exact");
        }

        assertFalse(byId.get("v2-mirror-no-pairs-refused").mirrored(),
                "a clip with no left/right names cannot be mirrored, so no second orientation is allowed");
        // Pins the real threshold: one pair produces two map entries and therefore clears
        // MIRROR_MIN_PAIRS, so the effective floor is one pair, not two. See the case note.
        assertTrue(byId.get("v2-mirror-single-pair-allowed").mirrored(),
                "one left/right pair clears the guard as implemented");
        assertFalse(byId.get("v2-mirror-orientation-loses").mirrored(),
                "an unrelated candidate must not be rescued by the mirrored orientation");

        MotionComparisonV2Result exact = byId.get("v2-mirror-exact-short-circuits");
        assertTrue(exact.exactCurveData(), "identical curve data should still report exact");
        assertFalse(exact.mirrored(), "exactness must short-circuit before any mirror work");
        assertEquals(MotionVerdict.EXACT_CURVE_DATA, exact.verdict(),
                "the direct orientation's exact verdict must survive");
    }
}
