// core/src/test/java/creatorflow/motion/MotionParityOracleGeneratorTest.java
package creatorflow.motion;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

/**
 * Generates (UPDATE_MOTION_PARITY_ORACLE=1) or drift-guards the committed TS parity
 * oracle at frontend/src/motion/parity/motion-parity-oracle.json. The oracle records
 * the REAL engine's outputs; the TS port must reproduce them (motionParity.test.ts).
 * Never regenerate to make a failing TS parity test pass — that inverts the oracle.
 */
class MotionParityOracleGeneratorTest {

    private static final Path ORACLE_PATH =
            Path.of("..", "frontend", "src", "motion", "parity", "motion-parity-oracle.json");

    @Test
    void oracleMatchesTheCommittedFixture() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode oracle = mapper.createObjectNode();
        oracle.put("generatorNote",
                "Generated by MotionParityOracleGeneratorTest via mvn -pl core test; regenerate ONLY with UPDATE_MOTION_PARITY_ORACLE=1 and only to add cases.");
        oracle.put("javaVersion", System.getProperty("java.version"));
        oracle.put("osName", System.getProperty("os.name"));
        ArrayNode cases = oracle.putArray("cases");
        for (MotionParityOracle.OracleCase oracleCase : MotionParityOracle.cases()) {
            MotionComparisonResult result = MotionComparisonEngine.compare(
                    new MotionComparisonRequest(oracleCase.source(), oracleCase.candidate()));
            ObjectNode node = cases.addObject();
            node.put("id", oracleCase.id());
            node.put("description", oracleCase.description());
            node.set("source", mapper.valueToTree(oracleCase.source()));
            node.set("candidate", mapper.valueToTree(oracleCase.candidate()));
            node.set("result", mapper.valueToTree(result));
        }

        if ("1".equals(System.getenv("UPDATE_MOTION_PARITY_ORACLE"))) {
            Files.createDirectories(ORACLE_PATH.getParent());
            mapper.writerWithDefaultPrettyPrinter().writeValue(ORACLE_PATH.toFile(), oracle);
            return;
        }

        Assumptions.assumeTrue(Files.exists(ORACLE_PATH),
                "committed oracle not present (frontend tree unavailable); run with UPDATE_MOTION_PARITY_ORACLE=1 to create it");
        JsonNode committed = mapper.readTree(ORACLE_PATH.toFile());
        // javaVersion/osName may legitimately differ between machines; the cases must not.
        assertEquals(cases, committed.get("cases"),
                "oracle drift: MotionParityOracle cases or engine output changed without regenerating the fixture");
    }
}
